version: "3.7"

services:
  server:
    image: 899166649333.dkr.ecr.ap-northeast-2.amazonaws.com/mine-api:latest
    env_file:
      - secret.env
    ports:
      - 8080:8080
    volumes:
      - /home/ec2-user/docker/logs:/logs